# Generated by Django 4.1.7 on 2023-02-21 21:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klienci',
            old_name='login',
            new_name='author',
        ),
        migrations.AddField(
            model_name='pracownicy',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pracownicy',
            name='ilosc_ocen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='konta',
            name='id_klienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konta_klienta', to='core.klienci'),
        ),
        migrations.AlterField(
            model_name='konta',
            name='id_pracownika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konta_pracownika', to='core.pracownicy'),
        ),
        migrations.AlterField(
            model_name='konta',
            name='rodzaj_konta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rodzaje_kont', to='core.rodzaje_kont'),
        ),
        migrations.AlterField(
            model_name='konto_debetowe',
            name='saldo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='konto_kredytowe',
            name='saldo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='konto_walutowe',
            name='saldo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oceny_pracownikow',
            name='ocena',
            field=models.FloatField(max_length=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='transakcje',
            name='kwota',
            field=models.FloatField(),
        ),
    ]
