# Generated by Django 4.1.7 on 2023-02-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klienci',
            old_name='login',
            new_name='author',
        ),
    ]
