# Generated by Django 4.1.7 on 2023-02-21 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_login_klienci_author_pracownicy_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pracownicy',
            old_name='ilosc_ocen',
            new_name='nr_ocen',
        ),
        migrations.AddField(
            model_name='oceny_pracownikow',
            name='ilosc_ocen_pracownika',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ilosc_ocen', to='core.pracownicy'),
            preserve_default=False,
        ),
    ]
