# Generated by Django 4.1.7 on 2023-02-21 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pracownicy_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oceny_pracownikow',
            name='ocena',
            field=models.FloatField(max_length=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
